services:
  voicebox:
    build:
      context: .
      args:
        - LOG_LEVEL=${LOG_LEVEL:-info}
        - NUMBA_CACHE_DIR=${NUMBA_CACHE_DIR:-/tmp/numba_cache}
        - VOICEBOX_CORS_ORIGINS=${VOICEBOX_CORS_ORIGINS:-https://$SERVICE_FQDN_VOICEBOX}
        - VOICEBOX_FORCE_CPU=${VOICEBOX_FORCE_CPU:-1}
    container_name: voicebox
    restart: unless-stopped
    ports:
      - '${PORT_17493:-17493}:17493'
    volumes:
      - 'voicebox-output:/app/data/generations'
      - 'voicebox-data:/app/data'
      - 'huggingface-cache:/home/voicebox/.cache/huggingface'
    environment:
      - 'LOG_LEVEL=${LOG_LEVEL:-info}'
      - 'NUMBA_CACHE_DIR=${NUMBA_CACHE_DIR:-/tmp/numba_cache}'
      - 'VOICEBOX_CORS_ORIGINS=${VOICEBOX_CORS_ORIGINS:-https://$SERVICE_FQDN_VOICEBOX}'
      - 'VOICEBOX_FORCE_CPU=${VOICEBOX_FORCE_CPU:-1}'
    networks:
      - coolify

networks:
  coolify:
    external: true

volumes:
  voicebox-output: null
  voicebox-data: null
  huggingface-cache: null
